# config
bio: 'Make it easy, make it different, then make it. '

# Content
excerpt_link: Read More

# Sidebar
menu:
  Home: /
# Archives: /archives
  Blog: http://www.thonatos.com
  About: /about
  Projects: /projects

